version: '3.8'

services:
  todoapp-db:
    image: postgres:16-alpine
    container_name: todoapp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp_db
    ports:
      - "5432:5432"
    volumes:
      - todoapp_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  todoapp_postgres_data: